// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for User service

func NewUserEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for User service

type UserService interface {
	Create(ctx context.Context, in *UserInformation, opts ...client.CallOption) (*Response, error)
	Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*ListResponse, error)
	Update(ctx context.Context, in *UserInformation, opts ...client.CallOption) (*UserInformation, error)
	All(ctx context.Context, in *AllRequest, opts ...client.CallOption) (*ListResponse, error)
	Validate(ctx context.Context, in *UserInformation, opts ...client.CallOption) (*UserInformation, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) Create(ctx context.Context, in *UserInformation, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "User.Create", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*ListResponse, error) {
	req := c.c.NewRequest(c.name, "User.Search", in)
	out := new(ListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Update(ctx context.Context, in *UserInformation, opts ...client.CallOption) (*UserInformation, error) {
	req := c.c.NewRequest(c.name, "User.Update", in)
	out := new(UserInformation)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) All(ctx context.Context, in *AllRequest, opts ...client.CallOption) (*ListResponse, error) {
	req := c.c.NewRequest(c.name, "User.All", in)
	out := new(ListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Validate(ctx context.Context, in *UserInformation, opts ...client.CallOption) (*UserInformation, error) {
	req := c.c.NewRequest(c.name, "User.Validate", in)
	out := new(UserInformation)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for User service

type UserHandler interface {
	Create(context.Context, *UserInformation, *Response) error
	Search(context.Context, *SearchRequest, *ListResponse) error
	Update(context.Context, *UserInformation, *UserInformation) error
	All(context.Context, *AllRequest, *ListResponse) error
	Validate(context.Context, *UserInformation, *UserInformation) error
}

func RegisterUserHandler(s server.Server, hdlr UserHandler, opts ...server.HandlerOption) error {
	type user interface {
		Create(ctx context.Context, in *UserInformation, out *Response) error
		Search(ctx context.Context, in *SearchRequest, out *ListResponse) error
		Update(ctx context.Context, in *UserInformation, out *UserInformation) error
		All(ctx context.Context, in *AllRequest, out *ListResponse) error
		Validate(ctx context.Context, in *UserInformation, out *UserInformation) error
	}
	type User struct {
		user
	}
	h := &userHandler{hdlr}
	return s.Handle(s.NewHandler(&User{h}, opts...))
}

type userHandler struct {
	UserHandler
}

func (h *userHandler) Create(ctx context.Context, in *UserInformation, out *Response) error {
	return h.UserHandler.Create(ctx, in, out)
}

func (h *userHandler) Search(ctx context.Context, in *SearchRequest, out *ListResponse) error {
	return h.UserHandler.Search(ctx, in, out)
}

func (h *userHandler) Update(ctx context.Context, in *UserInformation, out *UserInformation) error {
	return h.UserHandler.Update(ctx, in, out)
}

func (h *userHandler) All(ctx context.Context, in *AllRequest, out *ListResponse) error {
	return h.UserHandler.All(ctx, in, out)
}

func (h *userHandler) Validate(ctx context.Context, in *UserInformation, out *UserInformation) error {
	return h.UserHandler.Validate(ctx, in, out)
}
